### ISSUE TITLE
not working with chrome, may be bug

### ISSUE THREAD

**Issue by hungminhtran** [luispabon/maximus-gnome-shell#12]
1. Open chrome, choose use system title bar, maximize it, then press alt + f4 to close.
2. open chrome again,  and the title just black, not hidden or disappear.

Some apps got this error, too: mysql workbench, kolour paint, sublime text 3 ... 
https://www.dropbox.com/s/pvrigv86pqqfk3b/maximus%20error.png?dl=0

**Comment by doppelhelix** [comment]
you can add those to the list (basically all GTK+ 2.x apps) :
- LibreOffice
- GIMP (multi-window mode)
- Shotwell
- Inkscape
- Thunderbird
- Transmission
- Brasero
- Puddletag
- Rhythmbox
- Enpass
- Seahorse

**Comment by luispabon** [comment]
Unfortunately most of the code relies on both X and gtk 3 to retrieve window properties and at this time it's not possible supporting non-gtk 3 apps. You might be luckier with the Pixel Saver extension however.
