### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fishears** [luispabon/maximus-gnome-shell#3]
Hi, I just installed on Ubuntu Gnome 15.10 and it can't be enabled and I get this error when clicking on settings:
Error: Schema org.gnome.shell.extensions.maximus could not be found for extension maximus@luis.pabon.auronconsulting.co.uk. Please check your installation.

Stack trace:
  getSettings@/home/jb/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/convenience.js:66
  MaximusPrefsWidget<._init@/home/jb/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/prefs.js:188
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/jb/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/prefs.js:326
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

If I move the two schema files into a "schemas" subfolder then the error goes away and I can access settings but still can't enable the extension.

**Comment by fishears** [comment]
OK, I restarted gnome shell and suddenly there are no problems...

**Comment by luispabon** [comment]
:+1:

**Comment by addadi** [comment]
tried to restart gnome session, deleted the extension and reinstalled and restarted again but I get the same error message
