### ISSUE TITLE
Not work in GS 3.18.2

### ISSUE THREAD

**Issue by ghost** [luispabon/maximus-gnome-shell#4]
Hi, the extension not work in GS 3.18.2, when click on setting button appear this message:

Error: Schema org.gnome.shell.extensions.maximus could not be found for extension maximus@luis.pabon.auronconsulting.co.uk. Please check your installation.

Stack trace:
  getSettings@/home/Myuser/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/convenience.js:66
  MaximusPrefsWidget<._init@/home/Myuser/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/prefs.js:188
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/Myuser/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/prefs.js:326
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

**Comment by luispabon** [comment]
:+1: I'll check

**Comment by simonbcn** [comment]
Same problem

**Comment by luispabon** [comment]
I've released a new version on extensions.gnome, could you pls give it a shot?

https://extensions.gnome.org/extension/1026/maximus-ng/

**Comment by nhr** [comment]
Very strange - I click the "On / Off" switch and then press the "Install" button in the confirmation pop, but then the "On / Off" switch just goes back to "Off" with no error message.

**Comment by ghost** [comment]
> Very strange - I click the "On / Off" switch and then press the "Install" button in the confirmation pop, but then the "On / Off" switch just goes back to "Off" with no error message.

Same issue :(

**Comment by shibotto** [comment]
```
Error: Schema org.gnome.shell.extensions.maximus-ng could not be found for extension maximus@luis.pabon.auronconsulting.co.uk. Please check your installation.

Stack trace:
  getSettings@/home/user/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/convenience.js:66
  MaximusPrefsWidget<._init@/home/user/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/prefs.js:188
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/prefs.js:326
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1
```

**Comment by cassfalg** [comment]
I think at least one issue is that the schema is not compiled. If I download the zip file, and install it manually with gnome-tweak-tool, there is an error about 
~/.local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/schemas/
gschemas.compiled not found.
Running glib-compile-schemas schemas/ fixes that. But it does not work nontheless, on Arch Linux with Gnome Shell 3.18.3.

**Comment by Cygn** [comment]
After installing from extensions.gnome.org
in .local/share/gnome-shell/extensions/maximus@luis.pabon.auronconsulting.co.uk/
mkdir schemas
mv gschemas.compiled schemas/

restart the shell.

**Comment by danielquinn** [comment]
@Cygn's trick worked for me, so I guess the only thing needed is to roll this into what's on extensions.gnome.org?

**Comment by luispabon** [comment]
Apologies, I've been on holiday for a while away from my computer. I believe this issue has been fixed on https://github.com/luispabon/maximus-gnome-shell/pull/5, I'm updating extensions.gnome as we speak.

**Comment by Yannik** [comment]
@luispabon No, it has not because I have not changed anything in regard to this issue. @Cygn correctly reports the cause: Due to the '-j' flag you added to the 'zip' call, all directory paths are lost. I will open a PR for this in a few minutes.
